### PR TITLE
Rakefile: LDFLAGS's -R flag is not supported on Linux, enable it only on OSX

### PR DESCRIPTION
**Pull request by kalbasit**
Rakefile: LDFLAGS's -R flag is not supported on Linux, enable it only on OSX

``` bash
$ rake
[snip]
./configure --prefix=/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3 --exec-prefix=/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3/xapian-core-1.2.3':
configure: error: C compiler cannot create executables
See `config.log' for more details.
rake aborted!
```

``` bash
$ cat xapian-core-*/config.log
[snip]
configure:3866: checking whether the C compiler works
configure:3888: gcc   -R/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3/lib conftest.c  >&5
gcc: error: unrecognized option '-R'
configure:3892: $? = 1
configure:3930: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "xapian-core"
| #define PACKAGE_TARNAME "xapian-core"
| #define PACKAGE_VERSION "1.2.3"
| #define PACKAGE_STRING "xapian-core 1.2.3"
| #define PACKAGE_BUGREPORT "http://xapian.org/bugs"
| #define PACKAGE_URL ""
| #define PACKAGE "xapian-core"
| #define VERSION "1.2.3"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3935: error: in `/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3/xapian-core-1.2.3':
configure:3939: error: C compiler cannot create executables
[snip]
```

### CODE REVIEW

**Comment by rlane** [comment]
I'm using binutils-2.21.1 and it supports -R. What linker are you using?

From ld(1):
"For compatibility with other ELF linkers, if the -R option is followed by a directory name, rather than a file name, it is treated as the -rpath option."

**Comment by kalbasit** [comment]
That is very weird, I'm using ArchLinux, it ship with binutils 2.21.1 as well, and I see the the -R option in `man ld` however if you look at the output above, the -R flag from LDFLAGS is passed to `gcc` instead of `ld`

``` bash
configure:3888: gcc   -R/home/wael/.dotfiles/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/xapian-full-1.2.3/lib conftest.c  >&5
gcc: error: unrecognized option '-R'
```

**Comment by kalbasit** [comment]
What's even weird is building the gem without my patch using `rake` works, but using `gem install` breaks, I don't know why...

**Comment by kalbasit** [comment]
@rlane The last patch worked as expected for me, instead of setting LDFLAGS for the entire process, I had to set it only before running `make`.. I'm not sure why xapian's configure script tries to pass it on to gcc command (which does not accept a -R option)

**Comment by sebbacon** [comment]
Just to confirm I'm getting the same error in Linux (Ubuntu 11.10).

The last patch works for me too.

**Comment by sebbacon** [comment]
However, everything appears to compile fine without this patch on Debian Squeeze.

**Comment by kalbasit** [comment]
Does it compile fine even with this patch on Squeeze ?

**Comment by foobacca** [comment]
Just another confirmation that this issue affects Ubuntu 11.10. There is a launchpad bug about it - https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/794373 - the advice from the maintainer was:

> GCC 4.6 does reject unknown options, previously passed to the linker. Either use -Wl,-R/lib, or just remove it. It's not needed here.

Ubuntu versions are:
- gcc (Ubuntu/Linaro 4.6.1-9ubuntu3) 4.6.1
- binutils 2.21.53.20110810-0ubuntu5

Not sure what the correct behaviour should be, but the build script seems to work fine without it.

Another person bitten by this on Arch: https://bbs.archlinux.org/viewtopic.php?pid=926929#p926929

**Comment by maca** [comment]
I still cannot install from rubygems repo, has the fix been released?

**Comment by sebbacon** [comment]
No, it's not been released.  See https://github.com/rlane/xapian-full/issues/5

On 16 April 2012 08:33, Macario Ortega
reply@reply.github.com
wrote:

> I still cannot install from rubygems repo, has the fix been released?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rlane/xapian-full/pull/4#issuecomment-5147137

## 

skype: seb.bacon
mobile: 07790 939224
land: 01531 671074

**Pull request merged**
